<a href="https://colab.research.google.com/github/aneelabashir786/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Creation

In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU")
  print(torch.cude.get_device_name(0))
else:
  print("CPU")

CPU


In [ ]:
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.1573, 0.3431, 0.2794],
        [0.2748, 0.9604, 0.9477]])

In [ ]:
torch.rand(2,3)

tensor([[0.4135, 0.1491, 0.5742],
        [0.1684, 0.1021, 0.0941]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3] , [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.full((2,2),3)

tensor([[3, 3],
        [3, 3]])

# Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[ 465382256,  463388016, 1065353216],
        [         0, 1065353216,         49]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
#torch.rand_like(x)       # fail because it generates float values between 0 and 1 but x is integer

torch.rand_like(x,dtype=torch.float32)


tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# DataTypes

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([[1.0,2.0,3.0] , [4.0,5.0,6.0]] , dtype = torch.int32 )

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [ ]:
# add
x+2
# sub
x-2
# mul
x*2
# div
x/2
# int div
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

In [ ]:
torch.abs(x)
torch.neg(x)
torch.round(x)
torch.ceil(x)
torch.floor(x)
torch.clamp(x , min = 0.2 , max = 0.8)
# sum of whole matrix
torch.sum(x)
torch.sum(x , dim =0 )
torch.sum(x,dim=1)
torch.mean(x)
torch .median(x)
torch.std(x)
torch.var(x)
torch.argmax(x)
torch.argmin(x)

tensor(2)

In [ ]:
x = torch.rand(2,3)
y = torch.rand(3,2)

torch.matmul(x,y)
torch.transpose(x , 0  ,1)

tensor([[0.2324, 0.1659],
        [0.9141, 0.4393],
        [0.7668, 0.2243]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

a>=b

a<=b

a==b

a!=b

tensor([[True, True, True],
        [True, True, True]])

# Inplace Operations

In [ ]:
a+b

tensor([[0.6651, 1.0172, 1.1338],
        [0.0292, 0.6475, 0.8410]])

In [ ]:
a.add_(b)

tensor([[0.6651, 1.0172, 1.1338],
        [0.0292, 0.6475, 0.8410]])

In [ ]:
a

tensor([[0.6651, 1.0172, 1.1338],
        [0.0292, 0.6475, 0.8410]])

# Copying a tensor

In [ ]:
c= torch.rand(3,3)
d=c
d

tensor([[0.2103, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953],
        [0.9991, 0.1133, 0.0135]])

In [ ]:
c[0][0] = 0

In [ ]:
c


tensor([[0.0000, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953],
        [0.9991, 0.1133, 0.0135]])

In [ ]:
d

tensor([[0.0000, 0.1292, 0.1719],
        [0.9127, 0.6818, 0.1953],
        [0.9991, 0.1133, 0.0135]])

In [ ]:
id(c)

131937263763856

In [ ]:
id(d)

131937263763856

In [ ]:
d = c.clone()

In [ ]:
id(c)

131937263763856

In [ ]:
id(d)

131937265719232

In [ ]:
# permute , sqeez and unsqueez functions  of reshape

# NUMPY AND TENSOR

In [ ]:
import numpy as np


a=torch.tensor([1,2,3])

b = a.numpy()

type(a)

c = np.array([1,2,3])

d = torch.from_numpy(c)

type(d)

torch.Tensor